using Org.BouncyCastle.Crypto.Digests;
using Org.BouncyCastle.Crypto.Parameters;
using Org.BouncyCastle.Pqc.Crypto.Falcon;
using Org.BouncyCastle.Security;
using System;
using System.Linq;

namespace Algorand.Algod.Model
{
    /// <summary>
    /// A post-quantum Falcon-1024 account ("f1" scheme, algod 5.0.0 / consensus v42).
    ///
    /// The account's address is derived from its Falcon-1024 public key together with the canonical
    /// 1-byte salt (the lowest salt whose derived address is not an Edwards25519 curve point - the
    /// node rejects non-compliant PQ authorizer addresses at admission). Signatures follow the
    /// deterministic Falcon profile's wire format ("unsalted" compressed format: 0xBA header,
    /// salt-version byte, compressed s2) and verify under go-algorand's falcon_det1024 verifier.
    ///
    /// Key material uses the same raw layout as go-algorand / `algokey pq`: a 1793-byte public key
    /// (0x0A header + modq-encoded h) and a 2305-byte private key (0x5A header + f || g || F), so
    /// keys generated elsewhere can be imported directly.
    ///
    /// Note: a transaction authorized by a Falcon-1024 pqsig owes an additional 2x the network min
    /// fee on top of the base fee (3x min fee in total for an otherwise plain transaction).
    /// </summary>
    public class FalconAccount
    {
        /// <summary>Size in bytes of a Falcon-1024 public key, including the 0x0A header byte.</summary>
        public const int PublicKeySize = 1793;
        /// <summary>Size in bytes of a Falcon-1024 private key, including the 0x5A header byte.</summary>
        public const int PrivateKeySize = 2305;
        /// <summary>Size in bytes of a keygen seed.</summary>
        public const int SeedSize = 32;

        private const byte PublicKeyHeader = 0x0A;  // 0x00 + logn(10)
        private const byte PrivateKeyHeader = 0x5A; // 0x50 + logn(10)
        private const int FLen = 640;               // trim_i8(f), 5 bits/coeff * 1024 / 8
        private const int GLen = 640;               // trim_i8(g)
        private const int BigFLen = 1024;           // trim_i8(F), 8 bits/coeff * 1024 / 8

        /// <summary>The full 1793-byte Falcon-1024 public key (0x0A header + h).</summary>
        public byte[] PublicKey { get; }

        /// <summary>The full 2305-byte Falcon-1024 private key (0x5A header + f || g || F).</summary>
        public byte[] PrivateKey { get; }

        /// <summary>The canonical address salt for this public key.</summary>
        public byte Salt { get; }

        /// <summary>The post-quantum account address.</summary>
        public Address Address { get; }

        /// <summary>Creates a new Falcon-1024 account from a fresh random seed.</summary>
        public FalconAccount() : this(RandomSeed()) { }

        /// <summary>
        /// Creates a Falcon-1024 account deterministically from a 32-byte seed. The seed-to-key
        /// derivation is specific to this SDK (SHAKE256-expanded into BouncyCastle's keygen); to
        /// interoperate with keys generated by other tools, import the raw key bytes instead.
        /// </summary>
        public FalconAccount(byte[] seed)
        {
            if (seed == null || seed.Length != SeedSize)
                throw new ArgumentException($"seed must be {SeedSize} bytes", nameof(seed));

            var kpg = new FalconKeyPairGenerator();
            kpg.Init(new FalconKeyGenerationParameters(new ShakeStreamRandom(seed), FalconParameters.falcon_1024));
            var kp = kpg.GenerateKeyPair();
            var priv = (FalconPrivateKeyParameters)kp.Private;
            var pub = (FalconPublicKeyParameters)kp.Public;

            PublicKey = WithHeader(PublicKeyHeader, pub.GetEncoded(), PublicKeySize);
            PrivateKey = WithHeader(PrivateKeyHeader, priv.GetEncoded(), PrivateKeySize);
            Salt = PQSignature.FindCanonicalSalt(PQSignature.SchemeFalcon1024, PublicKey, out var address);
            Address = address;
        }

        /// <summary>
        /// Imports an existing Falcon-1024 key pair in go-algorand / algokey raw layout
        /// (1793-byte public key with 0x0A header, 2305-byte private key with 0x5A header).
        /// </summary>
        public FalconAccount(byte[] publicKey, byte[] privateKey)
        {
            if (publicKey == null || publicKey.Length != PublicKeySize || publicKey[0] != PublicKeyHeader)
                throw new ArgumentException($"public key must be {PublicKeySize} bytes with 0x0A header", nameof(publicKey));
            if (privateKey == null || privateKey.Length != PrivateKeySize || privateKey[0] != PrivateKeyHeader)
                throw new ArgumentException($"private key must be {PrivateKeySize} bytes with 0x5A header", nameof(privateKey));

            PublicKey = (byte[])publicKey.Clone();
            PrivateKey = (byte[])privateKey.Clone();
            Salt = PQSignature.FindCanonicalSalt(PQSignature.SchemeFalcon1024, PublicKey, out var address);
            Address = address;
        }

        /// <summary>
        /// Signs raw message bytes (already carrying their domain-separation prefix, e.g.
        /// Transaction.BytesToSign()) and returns the complete "pqsig" authorization proof.
        /// </summary>
        public PQSignature SignPQRawBytes(byte[] data)
        {
            if (data == null) throw new ArgumentNullException(nameof(data));

            var skBody = PrivateKey.Skip(1).ToArray(); // f || g || F
            var skParams = new FalconPrivateKeyParameters(
                FalconParameters.falcon_1024,
                skBody.Take(FLen).ToArray(),
                skBody.Skip(FLen).Take(GLen).ToArray(),
                skBody.Skip(FLen + GLen).Take(BigFLen).ToArray(),
                PublicKey.Skip(1).ToArray());

            var salt = PQSignature.MakeSalt(PQSignature.DefaultSaltVersion);
            var signer = new FalconSigner();
            signer.Init(true, new ParametersWithRandom(skParams, new DetSigningRandom(salt, PrivateKey, data)));
            var detached = signer.GenerateSignature(data);

            return new PQSignature
            {
                Scheme = PQSignature.SchemeFalcon1024,
                Salt = Salt,
                PublicKey = (byte[])PublicKey.Clone(),
                Signature = PQSignature.RepackToUnsalted(detached, salt, PQSignature.DefaultSaltVersion),
            };
        }

        private static byte[] RandomSeed()
        {
            var seed = new byte[SeedSize];
            new SecureRandom().NextBytes(seed);
            return seed;
        }

        private static byte[] WithHeader(byte header, byte[] body, int expectedTotal)
        {
            if (body.Length != expectedTotal - 1)
                throw new InvalidOperationException($"unexpected key body length {body.Length}, want {expectedTotal - 1}");
            var full = new byte[expectedTotal];
            full[0] = header;
            Array.Copy(body, 0, full, 1, body.Length);
            return full;
        }

        /// <summary>
        /// SecureRandom whose entire output is the SHAKE256 stream of the given seed. Used to make
        /// key generation deterministic from a user seed.
        /// </summary>
        private sealed class ShakeStreamRandom : SecureRandom
        {
            private readonly ShakeDigest shake = new ShakeDigest(256);

            public ShakeStreamRandom(byte[] seed)
            {
                shake.BlockUpdate(seed, 0, seed.Length);
            }

            public override void NextBytes(byte[] buf) => shake.Output(buf, 0, buf.Length);
            public override void NextBytes(byte[] buf, int off, int len) => shake.Output(buf, off, len);
        }

        /// <summary>
        /// SecureRandom driving BouncyCastle's Falcon signer along the deterministic profile: the
        /// first 40-byte request (the signature nonce) receives the fixed versioned salt, and all
        /// further randomness (the Gaussian sampler seed) is drawn from SHAKE256(logn || privateKey
        /// || message), following falcon_det1024_sign_compressed. The node's verifier only checks
        /// the fixed salt, so signature validity does not depend on the sampler stream.
        /// </summary>
        private sealed class DetSigningRandom : SecureRandom
        {
            private readonly byte[] salt;
            private bool saltConsumed;
            private readonly ShakeDigest shake = new ShakeDigest(256);

            public DetSigningRandom(byte[] salt, byte[] privateKey, byte[] message)
            {
                this.salt = salt;
                shake.Update(10); // logn
                shake.BlockUpdate(privateKey, 0, privateKey.Length);
                shake.BlockUpdate(message, 0, message.Length);
            }

            public override void NextBytes(byte[] buf) => NextBytes(buf, 0, buf.Length);

            public override void NextBytes(byte[] buf, int off, int len)
            {
                if (!saltConsumed && len == salt.Length)
                {
                    Array.Copy(salt, 0, buf, off, len);
                    saltConsumed = true;
                    return;
                }
                shake.Output(buf, off, len);
            }
        }
    }
}
