using Algorand.Algod.Model;
using System;
using System.Threading.Tasks;

namespace sdk_examples
{
    /// <summary>
    /// Demonstrates backing up and recovering post-quantum Falcon-1024 accounts across Algorand
    /// tools and SDKs. Runs fully offline (no node needed).
    ///
    /// The cross-SDK standard (defined by go-algorand's `algokey pq`, adopted by official SDKs):
    ///   backup   = classic 25-word Algorand mnemonic encoding 32 bytes of entropy
    ///   recovery = keygen seed SHA-512/256("PQK" || scheme "f1" || entropy), then the
    ///              deterministic reference Falcon keygen (SHAKE256(seed)) regenerates the keys.
    ///
    /// The same account can therefore be moved between:
    ///   - this SDK:        FalconAccount.FromMnemonic(...) / account.ToMnemonic()
    ///   - go-algorand:     algokey pq import -m "..." --keyfile my.key
    ///                      algokey pq generate --keyfile my.key   (prints the mnemonic)
    ///   - js-algorand-sdk: v3.7.0-beta.1+ accepts the raw public key plus an external Falcon
    ///                      signer callback (see snippet at the bottom); the same mnemonic
    ///                      derivation can feed any reference-compatible Falcon implementation.
    /// </summary>
    public class FalconKeyInteropExample
    {
        // A key pair generated by go-algorand 5.0.0's `algokey pq generate`, which printed:
        //   PQ private key mnemonic: office route parade ... about clay
        //   PQ address salt: 0
        //   PQ address: HTKQVJJ3KYQDTRBAV2ZBHAHXCJKP2OXZXHJ4KQZFYDORVBOR676MY4NLQE
        private const string AlgokeyMnemonic =
            "office route parade much super sphere wheel morning spawn true wire already siren unveil planet damage basket depend undo deer acquire popular what about clay";
        private const string AlgokeyAddress =
            "HTKQVJJ3KYQDTRBAV2ZBHAHXCJKP2OXZXHJ4KQZFYDORVBOR676MY4NLQE";

        public static Task Main(string[] args)
        {
            // --- 1. Import: recover an account exported from algokey as a 25-word mnemonic. ---
            var imported = FalconAccount.FromMnemonic(AlgokeyMnemonic);
            Console.WriteLine("Recovered from algokey mnemonic:");
            Console.WriteLine($"  address:        {imported.Address}");
            Console.WriteLine($"  matches algokey: {imported.Address.ToString() == AlgokeyAddress}");
            Console.WriteLine($"  salt:           {imported.Salt}");

            // --- 2. Export: create a fresh account here and back it up as a mnemonic that ---
            // --- algokey (and any standard-following SDK) can import.                     ---
            var fresh = new FalconAccount();
            var mnemonic = fresh.ToMnemonic();
            Console.WriteLine();
            Console.WriteLine("New account (write the mnemonic down - it is the only backup):");
            Console.WriteLine($"  address:  {fresh.Address}");
            Console.WriteLine($"  mnemonic: {mnemonic}");
            Console.WriteLine();
            Console.WriteLine("Import it into a node with:");
            Console.WriteLine($"  algokey pq import -m \"{mnemonic}\" --keyfile my.key");
            Console.WriteLine("  algokey pq info --keyfile my.key   # shows the same PQ address");

            // Recovery round-trip: the mnemonic alone regenerates the identical key pair.
            var recovered = FalconAccount.FromMnemonic(mnemonic);
            Console.WriteLine($"  round-trip OK:  {recovered.Address.Equals(fresh.Address)}");

            // --- 3. Raw key transfer: for tools that exchange raw key bytes instead of      ---
            // --- mnemonics (algokey keyfiles, HSMs, js-algorand-sdk signer callbacks), the  ---
            // --- go-algorand layout is used directly: pk 1793 bytes (0x0A header), sk 2305  ---
            // --- bytes (0x5A header). Note raw imports carry no entropy, so they cannot be  ---
            // --- turned back into a mnemonic - keep the words safe.                         ---
            var pkB64 = Convert.ToBase64String(fresh.PublicKey);
            var skB64 = Convert.ToBase64String(fresh.PrivateKey);
            var rawImport = new FalconAccount(
                Convert.FromBase64String(pkB64), Convert.FromBase64String(skB64));
            Console.WriteLine();
            Console.WriteLine($"Raw key import round-trip OK: {rawImport.Address.Equals(fresh.Address)}");

            // --- 4. js-algorand-sdk (v3.7.0-beta.1+) interop -------------------------------
            // js ships the pqsig wire format but delegates the Falcon crypto to a callback, so
            // hand it the same raw public key and any det1024-compatible signer:
            //
            //   import { addressWithSignersFromRawFalcon1024Signer } from 'algosdk';
            //   const pqAccount = addressWithSignersFromRawFalcon1024Signer({
            //     falcon1024PublicKey: publicKey,           // the 1793 bytes exported above
            //     falcon1024Signer: async (bytesToSign) =>  // e.g. a WASM falcon-det1024 build
            //       falconDet1024SignCompressed(privateKey, bytesToSign),
            //   });
            //   // pqAccount.addr equals the address printed by this example and by algokey.
            //
            // A pqsig produced by this SDK's SignPQRawBytes(...) is exactly the deterministic
            // compressed format those verifiers (and the falcon_verify TEAL opcode) expect.

            return Task.CompletedTask;
        }
    }
}
